name: Build and Test BGMI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Clear pip cache to avoid old versions
      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      # 3️⃣ Set up Python 3.14
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      # 4️⃣ Create virtual environment
      - name: Create venv
        run: python3 -m venv venv

      # 5️⃣ Upgrade pip
      - name: Upgrade pip
        run: ./venv/bin/pip install --upgrade pip

      # 6️⃣ Install dependencies if requirements.txt exists
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            ./venv/bin/pip install -r requirements.txt
          fi

      # 7️⃣ Create bin folder
      - name: Create bin folder
        run: mkdir -p ./bin

      # 8️⃣ Compile C binary with pthread and math lib
      - name: Compile C binary
        run: gcc raj.c -o ./bin/bgmi -lm -lpthread

      # 9️⃣ Make binary executable
      - name: Make binary executable
        run: chmod +x ./bin/bgmi

      # 🔟 Test bgmi binary (no long-running execution)
      - name: Test bgmi binary
        run: ./bin/bgmi --help || echo "bgmi compiled successfully"

      # 1️⃣1️⃣ Run Python script
      - name: Run Python script
        run: ./venv/bin/python a.py
